CFLAGS=-std=c99 -Wall -pipe -O2 
DEFINES= 
LFLAGS=-lutil -ltermcap
PACKAGE=netnuke

all:
	cc -o $(PACKAGE) $(DEFINES) $(CFLAGS) $(LFLAGS) netnuke.c human_readable.c log.c 
	strip netnuke

clean:
	rm netnuke
